### ISSUE TITLE
Implement Login/Authentication functionality

### ISSUE THREAD

**Issue by m1n1** [mobileappdevhm20/team-project-team_7#21]
Acceptance: The user can enter his credentials and his credentials are checked if correct from the user databse

**Comment by m1n1** [comment]
Google Signup requires the app to be signed. 

[https://developers.google.com/android/guides/client-auth](url)
[https://developer.android.com/studio/publish/app-signing](url)

**Comment by devtobi** [comment]
@m1n1 Actually the app is being signed in the deployment pipeline 💯
