### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by devtobi** [mobileappdevhm20/team-project-team_7#26]
The README has to be made more informational.
Maybe take a look at other projects on GitHub for inspiration?

Description, Feature List, Screenshots, Authors, important milestones should be in the Readme..
Should also mention it was created as part of a class in university (and mention the class and university)

Maybe additionally find some more things

**Comment by C-RJonsson** [comment]
README is updated with more information about our project.
Screenshots of the Fimga prototype is missing right now.

**Comment by devtobi** [comment]
I would not add screenshots of the figma prototype but screenshots of the final product.

**Comment by C-RJonsson** [comment]
Final screenshots of the FiTrack app was added (homepage, workout, workout summary, and past workouts) to README.
