### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by devtobi** [mobileappdevhm20/team-project-team_7#28]
A small presentation (10 minutes ) with Google Slides should be made
It has to cover the following:
- demo of the current state of the app
- functions/features completed compared to your horizontal prototype
-  show project board and comment on your teamwork
- results of testing on AWS Device Farm
- outlook on how to complete your app this semester

**Comment by C-RJonsson** [comment]
A Google presentation created with all the criterias above. To present the sprint 2, on Friday 26/6.

**Comment by devtobi** [comment]
Do you have a link? Or maybe attach it to the documentation?
