### ISSUE TITLE
AWS device farm integration

### ISSUE THREAD

**Issue by devtobi** [mobileappdevhm20/team-project-team_7#30]
Research on how to setup a AWS device farm for a project
(Christopher)

Integrate it into the CodeMagic pipeline.
(Tobias)

**Comment by C-RJonsson** [comment]
I created a AWS team project in Device Farm.
Access keys generated to put in CodeMagic.

**Comment by devtobi** [comment]
ntegrating the AWS Device Farm into the codemagic pipeline by using the access keys worked.
By using a sylph.yaml configuration file in the project root. Device pools and test pools for testing can be defined.
However when running the build, strange test errors appear inside the AWS Device Farm log which have nothing to do with our flutter code.
We are going to switch back to using an android emulator for the driver tests.
